version: '3.7'

services:
  mongo:
    container_name: Reference-Mongo
    image: mongo:6.0.5
    restart: always
    ports:
      - ${PORT_MONGO}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

  mongo-express:
    container_name: Reference-MongoExpress
    image: mongo-express:latest
    restart: always
    ports:
      - ${PORT_ADMIN}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${USER_NAME}:${PASSWORD}@mongo:27017/
