version: '3'

services:
  elasticsearch:
    container_name: Reference-ElasticSearch
    image: elasticsearch:7.17.10
    restart: always
    ports:
      - ${ELASTIC_SEARCH_PORT_1}:9200
      - ${ELASTIC_SEARCH_PORT_2}:9300
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - Reference_ElasticSearch_Data:/usr/share/elasticsearch/data

  kibana:
    container_name: Reference-Kibana
    image: kibana:7.17.10
    restart: always
    ports:
      - ${KIBANA_PORT}:5601
    links:
      - elasticsearch

volumes:
  Reference_ElasticSearch_Data:
    driver: local
