version: '3.7'

volumes:
  Reference_Mysql_Db:
    driver: local

services:
  mysql:
    container_name: Reference-Mysql
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD} # user: root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - Reference_Mysql_Db:/var/lib/mysql
