version: '3.7'

services:
  minio:
    container_name: Reference-Minio
    image: minio/minio:RELEASE.2023-04-28T18-11-17Z
    volumes:
      - ./data/data:/data
      - ./data/config:/root/.minio
    environment:
      - MINIO_ACCESS_KEY=${ACCESS_KEY}
      - MINIO_SECRET_KEY=${SECRET_KEY}
    ports:
      - ${PORT_CORE}:9000
      - ${PORT_CONSOLE}:9091 # console
    command: ['server', '/data', '--address', ':9090', '--console-address', ':9091']
